sudo: false
language: perl
perl:
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
notifications:
  email:
    recipients:
      - olaf@wundersolutions.com
    on_success: always
    on_failure: always
before_install:
  - cpanm Code::TidyAll::Plugin::SortLines::Naturally
  - cpanm Code::TidyAll::Plugin::UniqueLines
  - eval $(curl https://travis-perl.github.io/init) --auto
cache:
  directories:
    - ~/perl5
